version: 2
jobs:
  download:
    docker:
      - image: centos:8
    steps:
      - checkout
      - run:
          name: Download and publish vault-helm chart
          command: |
            VAULT_HELM_VERSION=$(cat version)
            curl -fsSL -o vault-helm-$VAULT_HELM_VERSION.tgz https://codeload.github.com/hashicorp/vault-helm/tar.gz/v$VAULT_HELM_VERSION     
      - persist_to_workspace:
          root: ~/
          paths: 
            - ./
  publish:
    docker:
      - image: centos:8
    steps:
      - attach_workspace:
          at: ~/
      - run:
        name: Install jfrog
        command: |
          curl -fsSL -o /usr/local/bin/jfrog https://bintray.com/jfrog/jfrog-cli-go/download_file?file_path=1.33.2%2Fjfrog-cli-linux-386%2Fjfrog
          chmod +x /usr/local/bin/jfrog
      - run:
          name: publish chart
          command: |
            jfrog rt upload vault-helm-$VAULT_HELM_VERSION.tgz helm-local/ --url https://takescoop.jfrog.io/takescoop/ --user $DOCKER_REGISTRY_USERNAME --apikey $DOCKER_REGISTRY_PASSWORD --dry-run
workflows:
  version: 2
  download_publish:
    jobs:
      - download:
          context: publish
      - publish:
          context: publish
          requires: 
            - download
          # filters:
          #   branches:
          #     only: master
