version: 2
jobs:
  publish:
    docker:
      - image: centos:8
    steps:
      - checkout
      - run:
          name: Install jfrog
          command: |
            curl -fsSL -o /usr/local/bin/jfrog https://bintray.com/jfrog/jfrog-cli-go/download_file?file_path=1.33.2%2Fjfrog-cli-linux-386%2Fjfrog
            chmod +x /usr/local/bin/jfrog
      - run:
          name: Download and publish vault-helm chart
          command: |
            VAULT_HELM_VERSION=$(cat version)
            echo $VAULT_HELM_VERSION
workflows:
  version: 2
  build_and_test:
    jobs:
      - publish:
          context: publish
          # filters:
          #   branches:
          #     only: master
            # curl -fsSL https://github.com/hashicorp/vault-helm/archive/v$VAULT_HELM_VERSION.tar.gz -o ./vault-helm-$VAULT_HELM_VERSION.tgz
            # jfrog rt upload *.tgz helm-local/ --url https://takescoop.jfrog.io/takescoop/ --user $DOCKER_REGISTRY_USERNAME --apikey $DOCKER_REGISTRY_PASSWORD

