{{ if and .Values.scoop.serverCert .Values.scoop.serverKey }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.scoop.serverPKISecretName }}
  namespace: {{ .Release.Namespace }}
data:
  server-cert.pem: {{ .Values.scoop.serverCert}}
  server-key.pem: {{ .Values.scoop.serverKey}}
{{ end }}